### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/TestMod#4]
Please post high resolution photos of front and back side of PCB. And post photo of stack of PCBs for contract accounting.  

> TestMod v2.0: print 6 PCBs, stuff 6

**Comment by akaminska** [comment]
![IMG_20191129_145509](https://user-images.githubusercontent.com/45766037/78688936-15211900-78f6-11ea-9a2c-2a85b6260cfd.jpg)
![IMG_20191129_145517](https://user-images.githubusercontent.com/45766037/78688943-181c0980-78f6-11ea-9316-f006784dab55.jpg)

**Comment by jbqubit** [comment]
Thank you!
